"""Type stubs for pyuppsala.etree - the lxml.etree-compatible API."""

from __future__ import annotations

from typing import Any, Callable, Iterable, Iterator, Optional, Union

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class LxmlError(Exception): ...

Error = LxmlError

class XMLSyntaxError(LxmlError, SyntaxError): ...

ParseError = XMLSyntaxError

class XPathError(LxmlError): ...
class XPathEvalError(XPathError): ...
class XPathSyntaxError(XPathError, SyntaxError): ...
class DocumentInvalid(LxmlError): ...
class XMLSchemaParseError(LxmlError): ...
class XSLTError(LxmlError): ...
class XSLTParseError(XSLTError): ...
class XSLTApplyError(XSLTError): ...
class XIncludeError(LxmlError): ...

# ---------------------------------------------------------------------------
# Namespaces / QName
# ---------------------------------------------------------------------------

def register_namespace(prefix: str, uri: str) -> None: ...

class QName:
    text: str
    namespace: Optional[str]
    localname: str
    def __init__(
        self, text_or_uri_or_element: Any, tag: Optional[str] = None
    ) -> None: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

# ---------------------------------------------------------------------------
# Elements
# ---------------------------------------------------------------------------

_TagName = Union[str, QName]

class _Element:
    tag: Any
    text: Optional[str]
    tail: Optional[str]
    @property
    def attrib(self) -> _Attrib: ...
    @property
    def nsmap(self) -> dict[Optional[str], str]: ...
    @property
    def prefix(self) -> Optional[str]: ...
    @property
    def sourceline(self) -> Optional[int]: ...
    @property
    def base(self) -> Optional[str]: ...
    # attributes
    def get(self, key: _TagName, default: Any = None) -> Any: ...
    def set(self, key: _TagName, value: str) -> None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    # sequence protocol
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_Element]: ...
    def __getitem__(self, index: Union[int, slice]) -> Any: ...
    def __setitem__(self, index: int, element: _Element) -> None: ...
    def __delitem__(self, index: Union[int, slice]) -> None: ...
    def __contains__(self, element: object) -> bool: ...
    def index(
        self, child: _Element, start: Optional[int] = None, stop: Optional[int] = None
    ) -> int: ...
    # mutation
    def append(self, element: _Element) -> None: ...
    def extend(self, elements: Iterable[_Element]) -> None: ...
    def insert(self, index: int, element: _Element) -> None: ...
    def remove(self, element: _Element) -> None: ...
    def replace(self, old_element: _Element, new_element: _Element) -> None: ...
    def addnext(self, element: _Element) -> None: ...
    def addprevious(self, element: _Element) -> None: ...
    def makeelement(
        self,
        _tag: _TagName,
        attrib: Optional[dict[str, str]] = None,
        nsmap: Optional[dict[Optional[str], str]] = None,
        **extra: str,
    ) -> _Element: ...
    # navigation
    def getparent(self) -> Optional[_Element]: ...
    def getnext(self) -> Optional[_Element]: ...
    def getprevious(self) -> Optional[_Element]: ...
    def getroottree(self) -> _ElementTree: ...
    def itersiblings(
        self, tag: Optional[str] = None, preceding: bool = False
    ) -> Iterator[_Element]: ...
    def iterancestors(self, tag: Optional[str] = None) -> Iterator[_Element]: ...
    def iterdescendants(self, tag: Optional[str] = None) -> Iterator[_Element]: ...
    # traversal & search
    def iter(self, tag: Optional[str] = None) -> Iterator[_Element]: ...
    def itertext(self) -> Iterator[str]: ...
    def find(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> Optional[_Element]: ...
    def findall(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> list[_Element]: ...
    def findtext(
        self,
        path: str,
        default: Any = None,
        namespaces: Optional[dict[str, str]] = None,
    ) -> Any: ...
    def iterfind(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> Iterator[_Element]: ...
    def xpath(
        self,
        _path: str,
        namespaces: Optional[dict[str, str]] = None,
        smart_strings: bool = True,
        **variables: Any,
    ) -> Any: ...
    def xinclude(self) -> None: ...

class _Attrib:
    def __getitem__(self, key: _TagName) -> str: ...
    def __setitem__(self, key: _TagName, value: str) -> None: ...
    def __delitem__(self, key: _TagName) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def get(self, key: _TagName, default: Any = None) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def update(self, other: Any) -> None: ...

# ---------------------------------------------------------------------------
# Factories
# ---------------------------------------------------------------------------

def Element(
    _tag: _TagName,
    attrib: Optional[dict[str, str]] = None,
    nsmap: Optional[dict[Optional[str], str]] = None,
    **extra: str,
) -> _Element: ...
def SubElement(
    _parent: _Element,
    _tag: _TagName,
    attrib: Optional[dict[str, str]] = None,
    nsmap: Optional[dict[Optional[str], str]] = None,
    **extra: str,
) -> _Element: ...
def Comment(text: Optional[str] = None) -> _Element: ...
def ProcessingInstruction(target: str, text: Optional[str] = None) -> _Element: ...

PI = ProcessingInstruction

def iselement(element: object) -> bool: ...

# ---------------------------------------------------------------------------
# ElementTree
# ---------------------------------------------------------------------------

class DocInfo:
    @property
    def doctype(self) -> str: ...

class _ElementTree:
    def getroot(self) -> Optional[_Element]: ...
    @property
    def docinfo(self) -> DocInfo: ...
    def parse(
        self, source: Any, parser: Optional[XMLParser] = None, base_url: Optional[str] = None
    ) -> _Element: ...
    def xinclude(self) -> None: ...
    def write(
        self,
        file: Any,
        encoding: Optional[str] = None,
        xml_declaration: Optional[bool] = None,
        pretty_print: bool = False,
        **kwargs: Any,
    ) -> None: ...
    def find(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> Optional[_Element]: ...
    def findall(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> list[_Element]: ...
    def findtext(
        self,
        path: str,
        default: Any = None,
        namespaces: Optional[dict[str, str]] = None,
    ) -> Any: ...
    def iterfind(
        self, path: str, namespaces: Optional[dict[str, str]] = None
    ) -> Iterator[_Element]: ...
    def iter(self, tag: Optional[str] = None) -> Iterator[_Element]: ...
    def xpath(
        self,
        path: str,
        namespaces: Optional[dict[str, str]] = None,
        smart_strings: bool = True,
        **variables: Any,
    ) -> Any: ...
    def getpath(self, element: _Element) -> str: ...

def ElementTree(
    element: Optional[_Element] = None,
    *,
    file: Any = None,
    parser: Optional[XMLParser] = None,
) -> _ElementTree: ...

# ---------------------------------------------------------------------------
# Parsing & serialization
# ---------------------------------------------------------------------------

class XMLParser:
    def __init__(
        self,
        *,
        huge_tree: bool = False,
        remove_comments: bool = False,
        remove_pis: bool = False,
        strip_cdata: bool = True,
        resolve_entities: bool = True,
        no_network: bool = True,
        recover: bool = False,
        dtd_validation: bool = False,
        load_dtd: bool = False,
        ns_clean: bool = False,
        encoding: Optional[str] = None,
        max_depth: Optional[int] = None,
        max_entity_expansion: Optional[int] = None,
        namespace_aware: Optional[bool] = None,
        forbid_dtd: bool = False,
        forbid_entities: bool = False,
        collect_ids: bool = True,
        compact: bool = True,
        target: Any = None,
        resolvers: Any = None,
    ) -> None: ...

def fromstring(
    text: Union[str, bytes], parser: Optional[XMLParser] = None
) -> _Element: ...
def fromstringlist(
    strings: Iterable[Union[str, bytes]], parser: Optional[XMLParser] = None
) -> _Element: ...

XML = fromstring

def parse(
    source: Any, parser: Optional[XMLParser] = None, base_url: Optional[str] = None
) -> _ElementTree: ...
def tostring(
    element_or_tree: Union[_Element, _ElementTree],
    encoding: Optional[str] = None,
    method: str = "xml",
    xml_declaration: Optional[bool] = None,
    pretty_print: bool = False,
    doctype: Optional[str] = None,
    **kwargs: Any,
) -> Union[str, bytes]: ...
def tounicode(element_or_tree: Union[_Element, _ElementTree], **kwargs: Any) -> str: ...
def dump(elem: Union[_Element, _ElementTree], *, pretty_print: bool = True, **kwargs: Any) -> None: ...
def indent(
    tree: Union[_Element, _ElementTree], space: str = "  ", level: int = 0
) -> None: ...

# ---------------------------------------------------------------------------
# XPath helpers & validation
# ---------------------------------------------------------------------------

class XPath:
    path: str
    def __init__(
        self, path: str, namespaces: Optional[dict[str, str]] = None, **kwargs: Any
    ) -> None: ...
    def __call__(
        self, element_or_tree: Union[_Element, _ElementTree], **variables: Any
    ) -> Any: ...

class ETXPath(XPath): ...

def XPathEvaluator(
    element_or_tree: Union[_Element, _ElementTree],
    namespaces: Optional[dict[str, str]] = None,
    **kwargs: Any,
) -> Callable[..., Any]: ...

class XMLSchema:
    error_log: list[Any]
    def __init__(
        self,
        etree: Optional[_Element] = None,
        *,
        file: Any = None,
        base_path: Optional[str] = None,
    ) -> None: ...
    def validate(self, tree: Union[_Element, _ElementTree]) -> bool: ...
    def assertValid(self, tree: Union[_Element, _ElementTree]) -> None: ...
    def __call__(self, tree: Union[_Element, _ElementTree]) -> bool: ...

class _XSLTResultTree:
    def getroot(self) -> _Element: ...
    def write(self, file: Any, **kwargs: Any) -> Any: ...
    def __str__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __getattr__(self, name: str) -> Any: ...

class XSLT:
    error_log: list[Any]
    def __init__(
        self,
        xslt_input: Union[_Element, _ElementTree],
        *,
        extensions: Any = None,
        regexp: bool = True,
        access_control: Any = None,
    ) -> None: ...
    def __call__(
        self, _input: Union[_Element, _ElementTree], profile_run: bool = False, **kwargs: Any
    ) -> _XSLTResultTree: ...
    @staticmethod
    def strparam(value: Any) -> str: ...
